### ISSUE TITLE
看你图片，鼻子点的位置都歪了？

### ISSUE THREAD

**Issue by Dian-Yi** [arnejad/Facial-Keypoint-Detection#3]
这个是图片数据，用lstm效果肯能不太好，有训练过视频数据么？

**Comment by arnejad** [comment]
Thanks for your interest in this repository.

I hope that the Google Translator has done a good job in translating you question since I am not familiar with Chinese.

The location of different parts of the face are not independent from one another. Our idea for developing such architecture was based on this fact. Since LSTM cells share their knowledge, this could be used in determining the location of facial keypoints not only based on the image but also using the location of other found keypoints.

We have not tried this architecture on video data, however, this was the intuition for our design. I hope this could help.

**Comment by Dian-Yi** [comment]
ths for your answer,i think lstm cell is well for stable facail points. if you only test it on images , maybe have a better perfance using other tricks.
